#!/opt/anaconda/bin/python

import site
import os
import sys

# add cioppy to the search path
sys.path.append('/usr/lib/ciop/python/')
import cioppy
ciop = cioppy.Cioppy() 

# add the local packages where ndvi package is deployed
site.addsitedir('/application/share/python/lib')
# import the ndvi package 
import ndvi

# write a log entry
ciop.log('INFO', 'Calculating NDVI')

# create a local output folder for the NDVI results
output_path = os.path.join(ciop.tmp_dir, 'output')
os.makedirs(output_path)

# input comes from STDIN (standard input)
for line in sys.stdin:

    # line contains a reference to a catalogue entry
    ciop.log('INFO', 'input: ' + line)
    
    # ciop.copy extracts the path from the reference and downloads the Landsat product
    local_path = ciop.copy(line, ciop.tmp_dir)

    # print the Landsat local path in the log
    ciop.log('DEBUG', 'local path:' + local_path)    
    
    # create the output name using the dc:identifier metadata field
    identifier = ciop.casmeta("dc:identifier", line)
    ciop.log('DEBUG', 'identifier: ' + identifier)

    output_name = os.path.join(output_path, identifier + '_ndvi.tif')
    ciop.log('DEBUG', 'output_name: ' + output_name)

    # calculate the NDVI
    obj = ndvi.GDALCalcNDVI()
    obj.calc_ndvi(local_path, output_name)

    # use ciop.publish to publish the NDVI result 
    # use the URL returned by ciop.publish as the catalogue online resource info
    pub = ciop.publish(output_name, driver='s3')

    ciop.log('DEBUG', pub)
    # create the NDVI result metadata information 
    # using ciop.casmeta function to access the input product metadata
    metadata = [ "ical:dtstart=" + ciop.casmeta("ical:dtstart", line), 
                "ical:dtend=" + ciop.casmeta("ical:dtend", line),
                "dc:identifier=" + identifier + "_NDVI",
                "dct:spatial=" + ciop.casmeta("dct:spatial", line), 
                "dclite4g:onlineResource=" + pub]

 
    ciop.log('DEBUG', 'Register the result in the sandbox catalogue')
    # use ciop.register providing the sandbox local catalogue and 
    # a series template
    ciop.register('http://localhost/catalogue/sandbox/rdf',
                    'file:///application/py-ndvi/etc/series.rdf',
                    metadata)

    ciop.publish(output_name, metalink=True)

ciop.log('INFO', 'Done my share of the work!')
