#!/opt/anaconda/bin/python

import site
import os
import sys
from os.path import basename

# add cioppy to the search path
import cioppy
ciop = cioppy.Cioppy() 

# add the local packages where ndvi package is deployed
site.addsitedir('/application/share/python/lib')
# import the ndvi package 
import ndvi

# write a log entry
ciop.log('INFO', 'Calculating NDVI')

# create a local output folder for the NDVI results
output_path = os.path.join(ciop.tmp_dir, 'output')
os.makedirs(output_path)

# input comes from STDIN (standard input)
for line in sys.stdin:

    # line contains a reference to a catalogue entry
    ciop.log('INFO', 'input: ' + line)
    
    # ciop.copy extracts the path from the reference and downloads the Landsat product
    local_path = ciop.copy(line, ciop.tmp_dir)

    # print the Landsat local path in the log
    ciop.log('DEBUG', 'local path:' + local_path)    
    
    # create the output name using the dc:identifier metadata field
    identifier =  os.path.splitext(basename(local_path))[0] 
    ciop.log('DEBUG', 'identifier: ' + identifier)

    output_name = os.path.join(output_path, identifier + '_ndvi.tif')
    ciop.log('DEBUG', 'output_name: ' + output_name)

    # calculate the NDVI
    obj = ndvi.GDALCalcNDVI()
    obj.calc_ndvi(local_path, output_name)

    # use ciop.publish to publish the NDVI result 
    # use the URL returned by ciop.publish as the catalogue online resource info
    pub = ciop.publish(output_name, driver='s3')

    ciop.publish(output_name, metalink=True)

ciop.log('INFO', 'Done my share of the work!')
